export default class GeometrySingleton {
    private static instance: GeometrySingleton;
    private constructor () {
        GeometrySingleton.instance = {
            "walls": {
              id: "walls-",
              name: "walls-",
              type: "wall",
              filetype: "obj",
              filename: "walls.obj",
              directory: "/geometry/env/labv2/",
              scale: 1.0,
            },
            "floors": {
              id: "floor-",
              name: "floor-",
              type: "floor",
              filetype: "obj",
              filename: "floors.obj",
              directory: "/geometry/env/labv2/",
              scale: 1.0,
            },
            "robot": {
              id: "robot-",
              name: "robot-",
              type: "robot",
              filetype: "obj",
              filename: "turtlebot.obj",
              directory: "/geometry/robots/turtlebot2/",
              scale: 0.001,
            },
            "baseball": {
              id: "baseball-",
              name: "baseball-",
              type: "object",
              filetype: "obj",
              filename: "baseball.obj",
              directory: "/geometry/objects/baseball/",
              scale: 0.001,
            },
            "box": {
              id: "box-",
              name: "box-",
              type: "object",
              filetype: "obj",
              filename: "box.obj",
              directory: "/geometry/objects/box/",
              scale: 0.001,
            },
            "bucket": {
              id: "bucket-",
              name: "bucket-",
              type: "object",
              filetype: "obj",
              filename: "bucket.obj",
              directory: "/geometry/objects/bucket/",
              scale: 0.001,
            },
            "cycle": {
              id: "cycle-",
              name: "cycle-",
              type: "object",
              filetype: "obj",
              filename: "cycle.obj",
              directory: "/geometry/objects/cycle/",
              scale: 0.001,
            },
            "chair": {
              id: "chair-",
              name: "chair-",
              type: "object",
              filetype: "obj",
              filename: "chair.obj",
              directory: "/geometry/objects/chair/",
              scale: 0.03,
            },
            "gas can": {
              id: "gas-can-",
              name: "gas-can-",
              type: "object",
              filetype: "obj",
              filename: "gas-can.obj",
              directory: "/geometry/objects/gas-can/",
              scale: 0.1,
            },
            "gloves": {
              id: "glove-",
              name: "glove-",
              type: "object",
              filetype: "obj",
              filename: "glove.obj",
              directory: "/geometry/objects/gloves/",
              scale: 0.01,
            },
            "hard hat": {
              id: "hard-hat-",
              name: "hard-hat-",
              type: "object",
              filetype: "obj",
              filename: "hard-hat.obj",
              directory: "/geometry/objects/hard-hat/",
              scale: 0.001,
            },
            "recycle bin": {
              id: "recycle-bin-",
              name: "recycle-bin-",
              type: "object",
              filetype: "obj",
              filename: "recycle bin.obj",
              directory: "/geometry/objects/recycle-bin/",
              scale: 0.001,
            },
            "playground-walls": {
              id: "playground-walls-",
              name: "playground-walls-",
              type: "wall",
              filetype: "obj",
              filename: "walls.obj",
              directory: "/geometry/env/playground/",
              scale: 1.0,
            },
            "playground-floor": {
              id: "playground-floor-",
              name: "playground-floor-",
              type: "floor",
              filetype: "obj",
              filename: "floors.obj",
              directory: "/geometry/env/playground/",
              scale: 1.0,
            },
            "y2e2-walls": {
              id: "y2e2-walls-",
              name: "y2e2-walls-",
              type: "wall",
              filetype: "obj",
              filename: "walls.obj",
              directory: "/geometry/env/y2e2/bullet/",
              scale: 1.0,
            },
            "y2e2-floor": {
              id: "y2e2-floor-",
              name: "y2e2-floor-",
              type: "floor",
              filetype: "obj",
              filename: "floors.obj",
              directory: "/geometry/env/y2e2/bullet/",
              scale: 1.0,
            },
            "cafe-walls": {
              id: "cafe-walls-",
              name: "cafe-walls-",
              type: "wall",
              filetype: "obj",
              filename: "cafe-walls.obj",
              directory: "/geometry/env/cafe/",
              scale: 1.0,
            },
            "cafe-floor": {
              id: "cafe-floor-",
              name: "cafe-floor-",
              type: "floor",
              filetype: "obj",
              filename: "cafe-floor.obj",
              directory: "/geometry/env/cafe/",
              scale: 1.0,
            },
            "bottleneck-walls": {
              id: "bottleneck-walls-",
              name: "bottleneck-walls-",
              type: "wall",
              filetype: "obj",
              filename: "bottleneck-walls.obj",
              directory: "/geometry/env/bottleneck/",
              scale: 1.0,
            },
            "bottleneck-floor": {
              id: "bottleneck-floor-",
              name: "bottleneck-floor-",
              type: "floor",
              filetype: "obj",
              filename: "bottleneck-floor.obj",
              directory: "/geometry/env/bottleneck/",
              scale: 1.0,
            },
            "platform-floor": {
              id: "platform-",
              name: "platform-",
              type: "floor",
              filetype: "obj",
              filename: "platform.obj",
              directory: "/geometry/env/platform/",
              scale: 1.0,
            },
        };
    }
    public static getInstance() : GeometrySingleton {
        if (!GeometrySingleton.instance) {
            return new GeometrySingleton();
        } else {
            return GeometrySingleton.instance;
        }
    }
}

