query GetMeshesBuilding($buildingId: String!) {
    meshesOfBuilding(buildingId: $buildingId) {
        id,
        x,
        y,
        z,
        theta,
        name,
        width,
        height,
        depth,
        scale,
        type,
        geometry {
          filetype
          filename
          directory
        }
        physics {
          collision
          stationary
        }
    }
}