query GetMesh {
    meshesCurrent(deleted: false) {
        id
        name
        type
        width
        height
        depth
        scale
        x
        y
        z
        theta
        geometry {
          filetype
          filename
          directory
        }
        physics {
          collision
          stationary
        }
    }
}