query GetMesh {
    meshesCurrent(deleted: false) {
        id,
        name,
        width,
        height,
        depth,
        scale,
        geometry {
          filetype
          filename
          directory
        }
        physics {
          collision
          stationary
        }
    }
}