subscription SubscribePointsOfRobot($id: String) {
    pointCloud(id: $id) {
        pointsGroup {
            position {
                x
                y
                z
            }
            attribute {
                r
                b
                g 
            }
        }
        robot {
          id
        }
  }
}
